POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name":"Dan Soohoo",
  "number":"123-456-789"
}
###
GET http://localhost:3001/api/persons
###
DELETE  http://localhost:3001/api/persons/1
